### PR TITLE
Added LICENSE file & header to README

### PR DESCRIPTION
**Pull request by Denperidge**
Two small changes! As described in one of the commits, its for less reliance on PDF/better screenreader support, as well as just generally being more in line with other open source projects!

### CODE REVIEW

**Comment by sunzhuoshi** [comment]
Sorry, I don't think dev team will accept this PR.

**Comment by cloudishBenne** [comment]
@sunzhuoshi Any news on this?
I have an additional question:
Is this license compatible to any OSI Approved Licenses?

**Comment by xessgamedev** [comment]
> @sunzhuoshi Any news on this? I have an additional question: Is this license compatible to any OSI Approved Licenses?

I'm not a license expert, but I think the answer should be no. You may check the details of LICENSE.pdf by yourself.

**Comment by xess-intel** [comment]
Not planning to accept this license format request

**Pull request closed without merging**
